---
- name: Install NGINX
  apt: name={{item}} state=present
  with_items:
   - nginx
  tags:
    - nginx-installation

- name: Create configurations
  file: path=/etc/nginx/{{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - "sites-available"
    - "sites-enabled"
  tags:
    - nginx-installation

