version: "3"

services:
    apache:
        build:
            context: ../data/apache/docker
            args:
                - PHP_VERSION=${PHP_VERSION}
        env_file: ../.env
        container_name: apache
        volumes:
            - ../data/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ${SITE_PATH}:/var/www/html


