version: "3"

services:
    nginx:
        build:
            context: ../data/nginx/docker
            args:
                - NGINX_VERSION=${NGINX_VERSION}
        env_file: ../.env
        container_name: nginx
        volumes:
            - ../data/nginx/conf.d:/etc/nginx/conf.d
            - ../data/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ${SITE_PATH}:/var/www/html


