---
- name: Install PHP Package for {{ansible_distribution}}
  yum: name={{item}} state=present enablerepo=remi enablerepo=remi-php81
  with_items:
   - php
   - php-common
   - php-cli
   - php-fpm
   - php-json
   - php-mysqli
   - php-curl
   - php-ldap
   - php-pdo
   - php-pear
   - php-gd
   - php-mbstring
   - php-xml
   - php-xmlrpc
   - php-bcmath
  tags:
    - php81-installation
