# server cleaup ...

---
- name: build on docker
  hosts: docker
  remote_user: root
  become: true
  gather_facts: false

  pre_tasks:
    - name: check python install
      import_tasks: 'checkenv.yml'

  vars_files:
    - vars/main.yml

  roles:
    - role: debian/common
      when: ansible_os_family == 'Debian'
    - role: redhat/common
      when: ansible_os_family == 'RedHat'


    - role: debian/nginx
      when: ansible_os_family == 'Debian'
    - role: redhat/nginx
      when: ansible_os_family == 'RedHat'


    - role: debian/php
      when: ansible_os_family == 'Debian'
    - role: redhat/php
      when: ansible_os_family == 'RedHat'
